vcverifier:
  deployment:
    image:
      repository: quay.io/fiware/vcverifier
      tag: 2.8.0
    logging:
      level: DEBUG
      jsonLogging: true
      logRequests: true
      pathsToSkip:
        - "/health"
    ssikit:
      auditorUrl: http://it-vcwaltid:7003
    verifier:
      tirAddress: http://satellite:6060/trusted_issuer/v3/issuers/
      did: did:key:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
    configRepo:
      configEndpoint: http://it-credentials-config-service:4040/
  service:
    type: LoadBalancer
    port: 7070